name: Scheduled Twitter Bot

on:
  schedule:
    - cron: '48 21 * * *'  # 3:18 AM IST
    - cron: '49 21 * * *'  # 3:19 AM IST
    - cron: '50 21 * * *'  # 3:20 AM IST
    - cron: '51 21 * * *'  # 3:21 AM IST
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node index.js
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
