name: Scheduled Twitter Bot

on:
  schedule:
    - cron: '30 2 * * *'  # 8 AM IST
    - cron: '30 3 * * *'  # 9 AM IST
    - cron: '30 12 * * *' # 6 PM IST
    - cron: '30 13 * * *' # 7 PM IST
    - cron: '30 15 * * *' # 9 PM IST    
    - cron: '30 18 * * *' # 12 Am IST    
    - cron: '30 19 * * *' # 1 AM IST    
    - cron: '30 20 * * *' # 2 AM IST    
    - cron: '30 22 * * *' # 4 AM IST    
    - cron: '30 0 * * *' # 6 AM IST    

  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run Twitter bot
        run: node index.js
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
